<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- SQLite ORM -->
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />

    <!-- Needed for FileSystem.AppDataDirectory -->
    <PackageReference Include="Microsoft.Maui.Essentials" Version="9.0.0" />
  </ItemGroup>
</Project>
	